# -*- coding: utf-8 -*-
"""MLSprayChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dokw2TQmslHjoctxrXxrcKv7p__kF6wo
"""

from google.colab import drive
import sys

# Mount Google Drive
drive.mount('/content/drive')

# Get the absolute path of the current folder
abspath_curr = '/content/drive/My Drive/Colab Notebooks/ML/Final Project'

# Get the absolute path of the deep utilities folder
abspath_util_deep = '/content/drive/My Drive/Colab Notebooks/ML/HW4'

import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline 

# Set matplotlib sizes
plt.rc('font', size=20)
plt.rc('axes', titlesize=20)
plt.rc('axes', labelsize=20)
plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)
plt.rc('legend', fontsize=20)
plt.rc('figure', titlesize=20)

# Commented out IPython magic to ensure Python compatibility.
# The magic below allows us to use tensorflow version 2.x
# %tensorflow_version 2.x 
import tensorflow_hub as hub
import tensorflow as tf
from tensorflow import keras

# The random seed
random_seed = 42

# Set random seed in tensorflow
tf.random.set_seed(random_seed)

# Set random seed in numpy
import numpy as np
np.random.seed(random_seed)

"""Data Pre Processing"""

# Commented out IPython magic to ensure Python compatibility.
# Change working directory to the absolute path of the deep utilities folder
# %cd $abspath_util_deep

# Import the deep utitilities
# %run pmlm_utilities_deep.ipynb